const PLUGIN_ID = "com.desain.peekaboo";
export const METADATA_KEY = `${PLUGIN_ID}/metadata`;
export const MESSAGE_CHANNEL = `${PLUGIN_ID}/message`;
export const LOCAL_STORAGE_STORE_NAME = `${PLUGIN_ID}/localStorage`;
export const TOOL_ID = `${PLUGIN_ID}/tool`;
export const TOOL_VISIBILITY_MODE_ID = `${PLUGIN_ID}/toolModeVisibility`;
export const TOOL_SETTINGS_ACTION_ID = `${PLUGIN_ID}/toolActionSettings`;
export const POPOVER_SETTINGS_ID = `${PLUGIN_ID}/popoverSettings`;
export const CONTEXT_MENU_ID = `${PLUGIN_ID}/contextMenu`;
